version: '3.6'
services:
    rabbitmq:
      image: rabbitmq:3-management-alpine
      container_name: 'rabbitmq'
      ports:
        - 5672:5672
        - 15672:15672
      volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
      networks:
        - rabbitmq_go_net
networks:
  rabbitmq_go_net:
    driver: bridge
#  postgres:
#    image: postgres
#    restart: always
#    environment:
#      - DATABASE_HOST=127.0.0.1
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=academico
#
#    ports:
#      - "5432:5432"
#    volumes:
#      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
#
#  pgadmin-compose:
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: "test@gmail.com"
#      PGADMIN_DEFAULT_PASSWORD: "test123!"
#    ports:
#      - "16543:80"
#    depends_on:
#      - postgres